name: fnesemu
description: A multiplatform NES Emulator written in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.5+0

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  file_picker: ^5.0.1
  js: ^0.6.3
  package_info_plus: ^1.0.6
  mp_audio_stream: ^0.1.2
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  import_path_converter: ^1.0.1

flutter:
  uses-material-design: true

import_path_converter:
  relative: true # true->相対パスに変換, false->パッケージパスに変換(デフォルト: false)
