# nekomimi-daimao/kanban_memo/.github/workflows/github-pages.yml
name: github pages

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --base-href /${{ steps.version.outputs.repository }}/

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./build/web

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./build/web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
